# Generated by Django 4.2.7 on 2023-11-13 13:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='mood',
            field=models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('anxious', 'Anxious'), ('excited', 'Excited'), ('tired', 'Tired'), ('neutral', 'Neutral'), ('other', 'Other')], default='neutral', max_length=20),
        ),
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
