# Generated by Django 4.2.7 on 2023-11-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_mood_note_title_alter_note_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='body_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='body_plain_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
