# Generated by Django 4.2.7 on 2023-11-20 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_note_body_html_note_body_plain_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='body_plain_text',
        ),
    ]
