# Generated by Django 4.2.7 on 2023-12-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_remove_note_body_plain_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='mood',
            field=models.CharField(choices=[('joy', 'Joy'), ('anger', 'Anger'), ('trust', 'Trust'), ('fear', 'Fear'), ('surprise', 'Surprise'), ('sadness', 'Sadness'), ('disgust', 'Disgust'), ('anticipation', 'Anticipation'), ('neutral', 'Neutral')], default='neutral', max_length=20),
        ),
    ]
