# Generated by Django 4.2.7 on 2023-12-05 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracking', '0002_timeentry_user_specified_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
