# Generated by Django 4.2.7 on 2023-12-05 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracking', '0003_alter_timeentry_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeentry',
            name='user_specified_duration',
        ),
    ]
