# Generated by Django 4.2.7 on 2023-12-05 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracking', '0004_remove_timeentry_user_specified_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='user_specified_duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
